#!/usr/bin/env bash
#
# setup script.
#
# What this does, in order:
#   1. Create a Python virtual environment in .venv/ (skipped if it already exists).
#   2. Install requirements.txt into it.
#   3. Walk you through writing a .env file with your NCBI + Google Cloud
#      credentials (skipped if .env already exists; pass --force-env to overwrite).
#   4. Run `gcloud auth application-default login` if you're not already logged in.
#   5. Run test_config.py to confirm everything loaded.
#
# Usage:
#   bash setup.sh                # interactive setup, default flags
#   bash setup.sh --force-env    # re-prompt for credentials even if .env exists
#   bash setup.sh --skip-gcloud  # don't attempt the gcloud auth step
#   bash setup.sh --no-test      # skip the final test_config.py run
#
# Re-runnable: detects existing state and skips finished steps.

set -e

# ── locate repo root, parse flags ────────────────────────────────────────────
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

FORCE_ENV=0
SKIP_GCLOUD=0
SKIP_TEST=0
for arg in "$@"; do
    case "$arg" in
        --force-env)   FORCE_ENV=1   ;;
        --skip-gcloud) SKIP_GCLOUD=1 ;;
        --no-test)     SKIP_TEST=1   ;;
        -h|--help)
            sed -n '1,/^set -e/p' "$0" | grep '^#'
            exit 0
            ;;
        *) echo "unknown flag: $arg (run with --help)" >&2; exit 1 ;;
    esac
done

say() { printf '\n\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2; exit 1; }

# ── 1. Python virtual environment ─────────────────────────────────────────────
say "Step 1/5  Python virtual environment"

PYTHON_BIN=""
for candidate in python3.11 python3.10 python3.12 python3.13 python3; do
    if command -v "$candidate" >/dev/null 2>&1; then
        PYTHON_BIN="$candidate"
        break
    fi
done
[ -n "$PYTHON_BIN" ] || die "no python3 found on PATH"

if [ ! -d ".venv" ]; then
    echo "    creating .venv with $PYTHON_BIN ($("$PYTHON_BIN" --version))"
    "$PYTHON_BIN" -m venv .venv
else
    echo "    .venv/ already exists, reusing"
fi
# shellcheck disable=SC1091
source .venv/bin/activate
echo "    active interpreter: $(which python) ($(python --version))"

# ── 2. Install dependencies ───────────────────────────────────────────────────
say "Step 2/5  Install requirements"
pip install --quiet --upgrade pip
pip install --quiet -r requirements.txt
echo "    requirements installed"

# ── 3. .env file ──────────────────────────────────────────────────────────────
say "Step 3/5  .env file"

if [ -f ".env" ] && [ "$FORCE_ENV" -eq 0 ]; then
    echo "    .env already exists, skipping. Pass --force-env to overwrite."
else
    if [ -f ".env" ]; then
        backup=".env.backup.$(date +%Y%m%d_%H%M%S)"
        cp .env "$backup"
        warn "existing .env backed up to $backup"
    fi

    cat <<'BANNER'

    You need credentials for two services:
      (a) NCBI — generate at https://www.ncbi.nlm.nih.gov/account/settings/
                  (sign in -> Account settings -> API Key Management -> Create)
      (b) Google Cloud — get the Project ID from the GCP console.
                  MedGemma endpoint is optional; press Enter to skip those.

    Inputs are NOT echoed. Press Enter to accept the default in [brackets].

BANNER

    read -r -p "    NCBI_EMAIL                  : " NCBI_EMAIL
    read -r -s -p "    NCBI_API_KEY                : " NCBI_API_KEY; echo
    read -r -p "    GCP_PROJECT_ID              : " GCP_PROJECT_ID
    read -r -p "    GCP_LOCATION                [us-east4]    : " GCP_LOCATION
    read -r -p "    GCP_ENDPOINT_ID             (optional)    : " GCP_ENDPOINT_ID
    read -r -p "    GCP_DEDICATED_DNS           (optional)    : " GCP_DEDICATED_DNS
    read -r -p "    GEMINI_LOCATION             [us-central1] : " GEMINI_LOCATION
    read -r -p "    GEMINI_MODEL                [gemini-2.5-flash] : " GEMINI_MODEL

    GCP_LOCATION=${GCP_LOCATION:-us-east4}
    GEMINI_LOCATION=${GEMINI_LOCATION:-us-central1}
    GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-flash}

    cat > .env <<ENV
# Generated by setup.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Never commit this file — it is in .gitignore.

# NCBI / PubMed
NCBI_EMAIL=$NCBI_EMAIL
NCBI_API_KEY=$NCBI_API_KEY

# Google Cloud — Vertex AI (Gemini)
GCP_PROJECT_ID=$GCP_PROJECT_ID
GCP_LOCATION=$GCP_LOCATION
GEMINI_LOCATION=$GEMINI_LOCATION
GEMINI_MODEL=$GEMINI_MODEL

# Google Cloud — MedGemma private endpoint (optional)
GCP_ENDPOINT_ID=$GCP_ENDPOINT_ID
GCP_DEDICATED_DNS=$GCP_DEDICATED_DNS

# LLM defaults
LLM_TEMPERATURE=0.0
LLM_MAX_TOKENS=800
ENV
    chmod 600 .env
    echo "    .env written (mode 600)"

    if [ -z "$NCBI_API_KEY" ] || [ -z "$GCP_PROJECT_ID" ]; then
        warn "NCBI_API_KEY or GCP_PROJECT_ID is empty — the pipeline will fail until these are set."
    fi
fi

# ── 4. gcloud auth ────────────────────────────────────────────────────────────
if [ "$SKIP_GCLOUD" -eq 1 ]; then
    say "Step 4/5  gcloud auth (skipped)"
else
    say "Step 4/5  gcloud auth"

    if ! command -v gcloud >/dev/null 2>&1; then
        warn "gcloud CLI not found on PATH."
        warn "Install: https://cloud.google.com/sdk/docs/install"
        warn "Then re-run:  gcloud auth application-default login"
    else
        if gcloud auth application-default print-access-token >/dev/null 2>&1; then
            echo "    application-default credentials already valid"
        else
            echo "    running: gcloud auth application-default login"
            gcloud auth application-default login || warn "gcloud auth failed (continuing anyway)"
        fi

        # Set active project to match .env, if we have one.
        if [ -f ".env" ]; then
            # shellcheck disable=SC2154
            project_from_env="$(grep -E '^GCP_PROJECT_ID=' .env | head -1 | cut -d= -f2-)"
            if [ -n "$project_from_env" ]; then
                gcloud config set project "$project_from_env" >/dev/null 2>&1 \
                    && echo "    gcloud project set to $project_from_env"
            fi
        fi
    fi
fi

# ── 5. Verify ─────────────────────────────────────────────────────────────────
if [ "$SKIP_TEST" -eq 1 ]; then
    say "Step 5/5  Verification (skipped)"
else
    say "Step 5/5  Verification"
    if python test_config.py; then
        echo
        echo "    Setup complete. Next steps:"
        echo "      source .venv/bin/activate"
        echo "      cd core && python eval_bench.py --strategy expand --limit 3   # smoke test"
        echo "      cd core && python app_ui.py                                   # full pipeline UI"
    else
        warn "test_config.py reported errors — review the output above and edit .env."
        exit 1
    fi
fi
